require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'SportApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Post Install processing for Flipper
  def flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name == 'YogaKit'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.1'
        end
      end
    end
  end

  target 'SportAppTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  IOS_VERSION = '11.0'

  post_install do |installer|
    flipper_post_install(installer)

    react_native_post_install(installer)

    #   installer.pods_project.targets.each do |target|
    #     target.build_configurations.each do |config|
    #       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    #       config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    #     end
    #   end
    #   installer.pods_project.build_configurations.each do |config|
    #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.3'
    #     config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    #     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    #   end
    # end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_VERSION
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
      end

      case target.name
      when 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end
  
  `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
end
